version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile

    command:  sh -c "
                    chmod +x entrypoint.sh &&
                    sh entrypoint.sh"

    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    expose:
      - 6379
  celery:
    build: ./
    command: [ "celery", "-A", "config", "worker", "--loglevel=info" ]
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis


volumes:
  postgres_data:
  redis-data:
